/* Script de remocao da base de dados */

DROP TABLE ORBITA_PLANETA;
DROP TABLE ORBITA_ESTRELA;
DROP TABLE SISTEMA;
DROP TABLE ESTRELA;
DROP TABLE PARTICIPA;
DROP TABLE HABITACAO;
DROP TABLE COMUNIDADE;
DROP TABLE DOMINANCIA;
DROP TABLE NACAO_FACCAO;
DROP TABLE FACCAO;
DROP TABLE LOG_TABLE;
DROP TABLE USERS;
DROP TABLE LIDER;
DROP TABLE NACAO;
DROP TABLE FEDERACAO;
DROP TABLE ESPECIE;
DROP TABLE PLANETA;

DROP SEQUENCE SEQ_USER_ID;

DROP FUNCTION PASSWORD_MD5;
DROP FUNCTION FUNC_VALIDA_USUARIO;
DROP FUNCTION FUNC_BUSCA_CARGO_USUARIO;
DROP FUNCTION FUNC_VALIDA_LIDER_FACCAO;

DROP PROCEDURE PROC_CRIA_USUARIOS_PADRAO;
DROP PROCEDURE PROC_INSERIR_LOG;

DROP PACKAGE PAC_FUNC_CIENTISTA;
DROP PACKAGE PAC_FUNC_COMANDANTE;
DROP PACKAGE PAC_FUNC_LIDER_FACCAO;

DROP VIEW VIEW_COMUNIDADE_CREDENCIADA;
