/* Script de remocao da base de dados */

DROP TABLE ORBITA_PLANETA;
DROP TABLE ORBITA_ESTRELA;
DROP TABLE SISTEMA;
DROP TABLE ESTRELA;
DROP TABLE PARTICIPA;
DROP TABLE HABITACAO;
DROP TABLE COMUNIDADE;
DROP TABLE DOMINANCIA;
DROP TABLE NACAO_FACCAO;
DROP TABLE FACCAO;
DROP TABLE LIDER;
DROP TABLE NACAO;
DROP TABLE FEDERACAO;
DROP TABLE ESPECIE;
DROP TABLE PLANETA;
